version: '3.9'

services:
    web:
        image: nginx:latest
        ports:
            - "50:50"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./app:/app
        networks:
            - development
    php:
        build:
            context: .
            dockerfile: PHP_CUSTOM.Dockerfile
        volumes:
            - ./app:/app
        networks:
            - development
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: '123456'
            MYSQL_DATABASE: 'testing'
        volumes:
            - ./mysqldata:/var/lib/mysql
        ports:
            - 3336:3336
        networks:
            - development
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8090:80
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        networks:
            - development
networks:
    development: 
        external: true
